### PR TITLE
Exception fix

### PR DESCRIPTION
**Pull request by Therzok**
You're testing if position > -1. That means last iteration will be position == 0. You then do position--, which makes position -1. Then look for character at position -1, which is unexistent in an array.

### CODE REVIEW

**Comment by haacked** [comment]
Mind adding a unit test that fails without this fix?

**Comment by Therzok** [comment]
A word that has 80 characters. Impossible case for real words, but for encoded texts, it is possible. I'll add an unit test in the PR.

**Comment by haacked** [comment]
Ha!

[Lopado­temacho­selacho­galeo­kranio­leipsano­drim­hypo­trimmato­silphio­parao­melito­katakechy­meno­kichl­epi­kossypho­phatto­perister­alektryon­opte­kephallio­kigklo­peleio­lagoio­siraio­baphe­tragano­pterygon](http://en.wikipedia.org/wiki/Lopado%C2%ADtemacho%C2%ADselacho%C2%ADgaleo%C2%ADkranio%C2%ADleipsano%C2%ADdrim%C2%ADhypo%C2%ADtrimmato%C2%ADsilphio%C2%ADparao%C2%ADmelito%C2%ADkatakechy%C2%ADmeno%C2%ADkichl%C2%ADepi%C2%ADkossypho%C2%ADphatto%C2%ADperister%C2%ADalektryon%C2%ADopte%C2%ADkephallio%C2%ADkigklo%C2%ADpeleio%C2%ADlagoio%C2%ADsiraio%C2%ADbaphe%C2%ADtragano%C2%ADpterygon)

**Comment by Therzok** [comment]
The tool seems to only keep the last sequence of 80 characters intact, and splits each character with a space. Need to see why this happens.

**Comment by Therzok** [comment]
Fixed this up. 3rd commit was something I had forgotten to commit in 2nd.

**Comment by haacked** [comment]
Looks great! Mind if I just give you commit access? All I request is to add tests to new commits and still do work in a branch with Pull Requests. :)

**Comment by Therzok** [comment]
Okay, I'll gladly accept this. I will add tests for new fixes. Do you mean branch on this repository and Pull Request from branch to master and merge them myself?

**Comment by haacked** [comment]
Yes! That's exactly what I mean. We call it the "GitHub Flow" for projects where a team all have commit access to the same repository. Create a branch for every new feature/bug fix. Submit a PR. After review, merge it in and delete the branch.

If I don't review in a day, just merge it anyways (I get busy) and I'll review it after the fact unless it's something you're unsure about and really want a review. :) So far your PRs give me good reason to just trust your changes. The review is mostly for my benefit.

**Comment by Therzok** [comment]
Okay, I get it! I see how it should be done and I will follow the pattern. Hope I help out more in the long run. I'm getting used to your coding style lately, since mine differs a tiny bit. I will ask questions when they are needed.

I'll get back to coding now. =D

**Comment by haacked** [comment]
I'm not even sure TextWrapper follows my style. Do you use ReSharper? Usually I have a team settings file that encapsulates my coding style. :) SeeGit is probably a better example.

**Comment by Therzok** [comment]
Seems I can learn quite a deal of things from you. Thanks for the tips.

**Pull request merged**
